// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6SDeJtOutqVz3aGczuLI_3KGFC8gH92k',
    appId: '1:513457801867:web:3b9f8481f0dc8665e7e28e',
    messagingSenderId: '513457801867',
    projectId: 'music-player-68eab',
    authDomain: 'music-player-68eab.firebaseapp.com',
    storageBucket: 'music-player-68eab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXhnzpWXCLB_f2JmOP6A2_H1AaEfDTY-0',
    appId: '1:513457801867:android:0d88e7e3d8e8145ee7e28e',
    messagingSenderId: '513457801867',
    projectId: 'music-player-68eab',
    storageBucket: 'music-player-68eab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYUQOhOmATKDNazmBga95TQjnH69ggnBM',
    appId: '1:513457801867:ios:41a299ee7c268344e7e28e',
    messagingSenderId: '513457801867',
    projectId: 'music-player-68eab',
    storageBucket: 'music-player-68eab.appspot.com',
    iosClientId: '513457801867-01jaskse3rdnigaos01nse8qjqfqbvtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYUQOhOmATKDNazmBga95TQjnH69ggnBM',
    appId: '1:513457801867:ios:41a299ee7c268344e7e28e',
    messagingSenderId: '513457801867',
    projectId: 'music-player-68eab',
    storageBucket: 'music-player-68eab.appspot.com',
    iosClientId: '513457801867-01jaskse3rdnigaos01nse8qjqfqbvtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
